### ISSUE TITLE
NuGet place fontawesome in /Content/FontAwesome ?

### ISSUE THREAD

**Issue by DianaLaa** [tiesont/Font.Awesome.Packages#1]
Hi, I've just installed the NuGet package for Font.Awesome 5. What I immediately notice is that I get all.css and all.js files in my main Content and Scripts directory. Mixed in with my own CSS files this makes no sense: all.css does not contain all the CSS for my project.

It would be very helpful if this could be moved to subdirectories Content/FontAwesome and Scripts/FontAwesome. Is that perhaps possible?

**Comment by tiesont** [comment]
I'll think about it, but normally similar packages just place all of their files directly in Content. I have no idea why the Font Awesome team decided to call that file all.css, but I do agree it's not the best name ever. I can move everything to a fontawesome folder (which I already do for the Sass and Less packages), but I'm somewhat loathe to change how the CSS package has always worked. I'll consider it, though.

RE your issue from the official repo, Dave created Font Awesome, which is why his name is included in the NuGet packages.

**Comment by DianaLaa** [comment]
I understand. Thanks for your reply.

**Comment by tiesont** [comment]
I went ahead and made this change since (if for no other reason) the Sass and Less packages already use the same structure.

You can download the packages here if you want to load them locally, or NuGet should have them indexed shortly.

**Comment by DianaLaa** [comment]
Great! Thanks

**Comment by DianaLaa** [comment]
We just used it in a project. Works great, thank you for the change!

**Comment by ianp-its** [comment]
This is a breaking change if you are using bundling in MVC. Prior to 5.4.1, the following worked:
`bundles.Add(new StyleBundle("~/Content/cssBundle").Include("~/Content/all.css"));`
Upgrading to 5.4.1 and changing to the new location thus:
`bundles.Add(new StyleBundle("~/Content/cssBundle").Include("~/Content/fontawesome/all.css"));`
cause the webfonts to be no longer found. If you have a fix, it would be appreciated. All other updates worked by just updating the nuget package. It's now broken for this use case.

**Comment by tiesont** [comment]
That's not really a use-case I thought of. The font path in the all.css file is relative, so if you just load ~/Content/fontawesome/all.css it works as-is, since the ../webfonts directory is a sibling of /fontawesome. I assume it breaks with the bundle you're building because the "containing" directory becomes /Content, so the font path resolves to the site root.

I've been trying to avoid modifying the files, but what would probably work (with the MVC (not Core) template) is to modify the path for the font files to resolve to the site root. Something like /webfonts/fa-brand, etc., and then move the /webfonts directory back to the root. If you want to try a pre-release version, I can create a patch update for 5.5.0 and push that out.

**Comment by tiesont** [comment]
@DianaKoenraadt  @eics-ips If you want to give it a go, I pushed this pre-release version out: https://www.nuget.org/packages/Font.Awesome/5.5.0.1-alpha-2

It moves the font files back out to the site root, but I tweaked the paths in the CSS files to point to the /webfonts directory, rather than ../webfonts.

This worked in a throw-away MVC project I just created, but I'd like some confirmation before I push a patch version out.

**Comment by ianp-its** [comment]
This doesn't work. If the web site is not in the root (e.g. http://localhost/testsite/) then the webfonts used to be referenced at in http://localhost/testsite/webfonts. Now they are referenced at http://localhost/webfonts, and so they can't be found.

**Comment by tiesont** [comment]
@eics-ips  Okay. Not sure exactly how to approach this. The reason I changed the package structure to begin with was due to the Font Awesome team making the regrettable decision to call their assembled/compiled CSS file `all.css` - that's pretty generic, and (as noted above) is fairly likely to collide with other files.

So, I have a few options:

1) Revert to the original package structure, names and all
2) Revert to the original package structure, but rename `all.css` and `all.min.css` to `fontawesome-all.css` (or something along those lines)
3) Figure out some magic way to make the font-face paths work regardless of where the CSS file is located.

@DianaKoenraadt Would `fontawesome-all.css` work for your use-case? If so, that's probably the simplest fix to make both cases work.

**Comment by DianaLaa** [comment]
fontawesome-all.css would work for our usecase.

**Comment by ianp-its** [comment]
@tiesont, I totally agree about the naming of the file to `all.css`. Not sure what their thinking was. My preference would be option 2, but it's your call. It would certainly be an improvement on just calling the css file `all.css`. I think with the limitations of CSS and bundling wrt file locations is going to make option 3 fairly hard to achieve.

**Comment by tiesont** [comment]
Okay, I've just pushed another pre-release version to NuGet, which will take a moment to index the update. With this change:

1) All Font Awesome CSS files are placed directly in the `Content` folder.
2) `webfonts` is placed directly in the site root
3) The JavaScript files are (still) placed in a `fontawesome` folder within `Scripts`.
4) `all.css` and `all.min.css` are renamed to `fontawesome-all.css` and `fontawesome-all.min.css`, respectively.

1 through 3 basically revert the package back to the 5.3 and lower layout.

I'm still not jazzed about the lack of namespacing in the rest of the Font Awesome files. It might be worth raising that as an issue on the Font Awesome repo, but I doubt they would change something that major at this point.

I'm going to hold off pushing this out to a "live" version until the next Font Awesome release. I'll push the packages here if you want to load them locally until then.

**Comment by ianp-its** [comment]
Ok, that all seems to work fine. Thanks.

**Comment by tiesont** [comment]
Versions 5.6.1 and 5.6.3 (there was no 5.6.2) have been pushed to NuGet. I'll reopen if necessary.
